# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2bae045b095c5c2acc0bc46b5c6c5ab5899c7b185e0e126b60cccaa6ca5a8f2c4c0564b04192234108dda5a31ae7c4e5dfff657812bda59fb0994fc8c789591

test:
  secret_key_base: d15425e33190b78e512d639b648fdb2b49906794d43e50ee5cc4f614ef4b5e088f53d7374b701b76bda4cf336a2729a145c0adf2ee1ca21806bed99d30b43fae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
